### ISSUE TITLE
organize repos and get their issues current

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/digitallinguistics.io#59]
- [x] assets
- [ ] dlx-api
- [ ] dlx-api-js
- [ ] dlx-api-node
- [ ] dlx-api-py
- [ ] dlx-api-rb
- [ ] dlx-app
- [ ] dlx-blog
- [ ] dlx-js
- [ ] dlx-login
- [ ] dlx-org
- [ ] dlx-py
- [ ] dlx-rb
- [x] dlx-spec
- [ ] dlx-writer
